version: '3.8'

services:
  config-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-engine
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - config-network

networks:
  config-network:
    driver: bridge